[package]
name = "ocmapgen"
version = "0.2.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.12"
error-chain = "0.8"

[build-dependencies]
gcc = "0.3"
cmake = "0.1"
regex = "0.2"
glob = "0.2"
bindgen = "0.22"
