[package]
name = "ocmapgen"
version = "0.4.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
image = "0.23"
error-chain = "0.12"
regex = "1.3"

[build-dependencies]
cc = "1.0"
cmake = "0.1"
regex = "1.3"
glob = "0.3"
