[package]
name = "ocmapgen-bin"
version = "0.2.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]

[[bin]]
name = "ocmapgen"
path = "src/main.rs"

[dependencies]
clap = "2.22"
image = "0.12"
error-chain = "0.10"
notify = "4.0"

[dependencies.ocmapgen]
path = ".."
version = "0.2"
